language: php

php:
  - 7.0
  - 7.1
  - 7.2

sudo: false

install: travis_retry composer install --no-interaction --prefer-dist --no-suggest

script:
  - mkdir -p build/logs 
  - vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml

after_script:
  - travis_retry php vendor/bin/php-coveralls --verbose
